apiVersion: v1
kind: Service
metadata:
  name: gitrepo-volume-service
spec:
  type: LoadBalancer
  externalTrafficPolicy: Local
  selector:
    app: gitrepo-volume
  ports:
    - port: 80
      targetPort: 80

