apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: default-policy-cluster-role
rules:
  - apiGroups: ['policy']
    resources: ['podsecuritypolicies']
    verbs: ['use']
    resourceNames:
      - default
